### ISSUE TITLE
Can't close windows (QuPath seems to depend on window manager)

### ISSUE THREAD

**Issue by andor-pierdelacabeza** [qupath/qupath#336]
QuPath windows seem like they don't have any option for closing them (i.e., "File / Quit...", a "Close" or "OK" button on modals...) and seems to depend on the window manager to draw "close buttons" on windows.

In tiling window managers, (or at least on i3 in my case), you don't have those buttons, and you can't exit the app or even any modal that opens over it (as the "Welcome" window on the 0.2.0 version)

Common keyboard shortcuts don't seem to work: Ctrl+x, Ctrl+q, Ctrl+w, q, w...

Tested on:

- Debian Linux 10
- i3 4.16
- QuPath 0.1.2 and 0.2.0-m2

Example:
![qupath](https://user-images.githubusercontent.com/2430915/60427144-5e6d6b00-9bf6-11e9-9646-b9e0d9676e49.png)

**Comment by petebankhead** [comment]
You should be able to double-click anywhere on the welcome message to close it (as it suggests... slightly non-obviously, as a reward for people who read it :)

Apart from that, I agree that QuPath probably ought to have _File &rarr; Quit_ option as well but the main issue seems to be more JavaFX than QuPath - see https://github.com/javafxports/openjdk-jfx/issues/222

General availability of OpenJDK 13 is currently listed for 17 September. Current plans are to use this for v0.2.0 and hopefully the issue will be addressed then.

**Comment by andor-pierdelacabeza** [comment]
Seems like the 'double click' works for the welcome message, but not for other dialogues (as the "system info"). Once I click it, I can't go back to the app again :'(

So, probably, some shortcuts would be handy.

**Comment by petebankhead** [comment]
I think it requires the fix in JavaFX - which appears to be coming soon. Adding shortcuts to the dialogs throughout QuPath would be a rather large task and add further messiness to the code that I'd rather avoid...

Does v0.1.2 have the same problem?

**Comment by andor-pierdelacabeza** [comment]
Yes. I'm just testing it and no combination of buttons (that I've tested: q, x, Esc, Ctr+x, Ctrl+w, Ctrl+q) seem to make it close. Being a "real" modal window, I can't click on anything back in the app.

(I say "real modal", because the welcome window doesn't capture the action, and you can keep clicking back in the app, so that isn't so critical for me)

**Comment by petebankhead** [comment]
Yes, I explicitly coded the startup message to respond to a double-click because it was so annoying to need to click more precisely.

In any case, the link I posted suggests it should be fixed in JavaFX 13, which QuPath will switch to whenever it's available in September. I wouldn't _really_ fancy trying to track down all modal dialogs in QuPath to add shortcuts to close them if a fix is imminent anyway.

In the meantime, I'd suggest trying v0.1.2. This might have other issues, but at least it uses JavaFX with JDK 8 and therefore may not suffer this specific problem.

**Comment by petebankhead** [comment]
I'd be very interested to know if the [JavaFX update v0.2.0-m5](https://github.com/qupath/qupath/releases/tag/v0.2.0-m5) has resolved this.

**Comment by andor-pierdelacabeza** [comment]
I'll test it next week :)

**Comment by petebankhead** [comment]
Can this issue be closed?

**Comment by andor-pierdelacabeza** [comment]
I've downloaded _m6_ and it seems like I still have the same problem.

Also, when I click on the menus (File, Edit, Tools...) they close when I release the mouse button, they don't stay open to allow clicking on them.

**Comment by petebankhead** [comment]
Thanks @andor-pierdelacabeza for checking.
This seems to describe the menu issue: https://github.com/javafxports/openjdk-jfx/issues/546

**Comment by andor-pierdelacabeza** [comment]
It looks exactly like that!
